msgr/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views


app_name = "msgr"

urlpatterns = [
    path("",
         views.ChatsListView.as_view(),
         name="main"),
    path("users/",
         views.SearchView.as_view(),
         name="search"),
    path("users/<int:pk>/",
         views.ProfilePageView.as_view(),
         name="profile"),
    path("chats/",
         RedirectView.as_view(pattern_name="msgr:main", permanent=True),
         name="chats"),
    path("chats/<int:pk>/",
         views.ChatView.as_view(),
         name="chat"),
    path("chats/<int:pk>/messages/",
         views.ChatMessagesView.as_view(),
         name="messages"),
    path("chats/<int:pk>/updates/",
         views.ChatUpdatesView.as_view(),
         name="updates"),
    path("chats/delmessage/",
        views.ChatDeleteMessageView.as_view(),
        name="delete_message"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView

from accounts import views as account_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("",
         TemplateView.as_view(template_name="home.html"),
         name="home"),

    path("signup/",
         account_views.SignupView.as_view(),
         name="signup"),
    path("login/",
         auth_views.LoginView.as_view(next_page="profile"),
         name="login"),
    path("logout/",
         auth_views.LogoutView.as_view(next_page="home"),
         name="logout"),
    path("profile/",
         account_views.ProfileView.as_view(),
         name="profile"),

    path("password_reset/",
         auth_views.PasswordResetView.as_view(),
         name="password_reset"),
    path("password_reset/done/",
         auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("reset/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("reset/done/",
         auth_views.PasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
    # path("password_change/",
    #      auth_views.PasswordChangeView.as_view(),
    #      name="password_change"),
    # path("password_change/done/",
    #      auth_views.PasswordChangeDoneView.as_view(),
    #      name="password_change_done"),

    path("m/", include("msgr.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import re

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models


class UserManager(BaseUserManager):
    """Custom user model manager with email as the unique identifier."""

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """Custom user model with only email and password fields."""

    username = None
    first_name = None
    last_name = None
    email = models.EmailField("email address", unique=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self) -> str:
        return self.email


def validate_id(value):
    """Check if a user's id matches some criteria."""

    if not re.match(".{5,}", value):
        raise ValidationError("ID is too short.")
    if not re.match("(?!.*__.*)[a-zA-Z][\w_]*[^_ ]$", value):
        raise ValidationError("ID is invalid.")


class Profile(models.Model):
    """A user's profile information."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, default="new user")
    last_name = models.CharField(max_length=30, blank=True)
    identifier = models.CharField("id", max_length=30,
                                  unique=True, blank=True, null=True,
                                  validators=[validate_id])
    biography = models.CharField("bio", max_length=200, blank=True)
    picture = models.ImageField("pic", upload_to="profile_pics",
                                blank=True, null=True)

    def get_full_name(self):
        """Return the first_name plus the last_name,
        with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def clean(self):
        qs = Profile.objects.exclude(pk=self.pk).filter(
            identifier__iexact=self.identifier
        )
        if qs.exists():
            raise ValidationError({
                "identifier": "User with this Id already exists.",
            })
        super().clean()

    def __str__(self) -> str:
        return "%s profile" % self.user.get_username()

msgr/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Chat(models.Model):
    """Parent model representing a chat between multiple users.

    Direct instances of this class are private messages; which means
    the 'participants' relationship should only include two users.
    """

    participants = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                          through="Join", blank=True,
                                          related_name="chats")
    lat = models.DateTimeField("latest activity time", default=timezone.now)

    def update_lat(self):
        """Set latest activity time of the chat to now."""
        self.lat = timezone.now()
        self.save()

    def __str__(self) -> str:
        return "chat object (%s)" % self.pk


class Join(models.Model):
    """Intermediate model for relations between a user and a chat."""

    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name="+")
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name="joins")
    date_joined = models.DateField(auto_now_add=True)
    last_active = models.DateTimeField(default=timezone.now)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("user", "chat"),
                name="user_join_once_constraint"
            )
        ]

    def get_receivers(self):
        """Return all other users that are in the same chat."""
        return self.chat.participants.exclude(pk=self.user.pk)

    def get_profile(self):
        """Return a profile object containing
        additional data about the chat.
        """
        other = self.get_receivers()
        if other:
            return other.get().profile
        else:
            return self.user.profile

    def get_unread_count(self):
        """Return number of messages that has been sent since
        the last time user was in the chat.
        """
        unread_messages = self.chat.messages.filter(
            send_time__gt=self.last_active
        )
        return unread_messages.count()

    def update_last_active(self):
        """Set the last time user was in this chat to now."""
        self.last_active = timezone.now()
        self.save()


class Message(models.Model):
    """A message sent in a chat.

    Only the 'sender' is specified because 'chat' works as receivers,
    since audiences of a message are anyone else in the same chat.
    """

    chat = models.ForeignKey(Chat, on_delete=models.CASCADE,
                             related_name="messages")
    sender = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name="+")
    content = models.TextField()
    send_time = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    class Meta:
        ordering = ["send_time"]

    def __str__(self) -> str:
        return "message (%s) by %s in chat (%s)" % (
            self.pk,
            self.sender.get_username(),
            self.chat.pk
        )

msgr/forms.py
from django import forms

from .models import Message


class SearchForm(forms.Form):
    q = forms.CharField(strip=True, min_length=4)


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = (
            "content",
        )
        widgets = {
            "content": forms.Textarea(attrs={
                "id": "message-field",
                "required": True,
                "placeholder": "Message...",
                "rows": "1",
            }),
        }

msgr/templates/msgr/chat_page.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'msgr/css/chat_page.css' %}">
{% endblock %}

{% block title %}chat - msgr{% endblock %}
{% block h1 %}<h1>Chat room number {{ object.pk }}</h1>{% endblock %}

{% block content %}

<div id="delete-confirm" class="modal">
    <div class="modal-content">
        Delete this message?
        <button onclick="close_modal()">
            Cancel
        </button>
        <form id="delete-form">
            {% csrf_token %}
            <input type="hidden" name="message" id="delete-pk">
            <button type="submit" onclick="close_modal()">
                Delete
            </button>
        </form>
    </div>
</div>

<div id="messages-list">
</div>

<form id="message-form">
    {% csrf_token %}
    {{ form.content }}
    <input type="submit" value="Send" id="message-button">
</form>

<pre class="whitespace">





</pre>

{% endblock content %}

{% block javascript %}
<script>
    var full_path = "{{ request.get_full_path }}";
    var messages_path = "{% url 'msgr:messages' object.pk %}";
    var updates_path = "{% url 'msgr:updates' object.pk %}";
    var delete_message_path = "{% url 'msgr:delete_message' %}";
    var csrf_token = "{{ csrf_token }}";
</script>
<script src="{% static 'msgr/js/chatpage-date-headers.js' %}"></script>
<script src="{% static 'msgr/js/chatpage-get-updates.js' %}"></script>
<script src="{% static 'msgr/js/chatpage.js' %}"></script>
<script src="{% static 'msgr/js/chatpage-send-message.js' %}"></script>
<script src="{% static 'msgr/js/chatpage-delete-message.js' %}"></script>
{% endblock %}

msgr/templates/msgr/chats_list.html
{% extends 'base.html' %}
{% load static %}
{% load image_url_tags %}

{% block style %}
<link rel="stylesheet" href="{% static 'msgr/css/chats_list.css' %}">
<link rel="stylesheet" href="{% static 'msgr/css/search_form.css' %}">
{% endblock %}

{% block title %}chats - msgr{% endblock %}
{% block h1 %}<h1>Chats</h1>{% endblock %}

{% block content %}

{% include 'msgr/search_form.html' %}

{% for join in join_list %}
<div class="chat">
    {% with profile=join.get_profile %}
    <a href="{% url 'msgr:profile' profile.pk %}">
        <img src="{% get_profile_pic profile.picture True %}" alt="profile thumbnail" class="thumbnail">
    </a>
    <div class="chat-title">
        <a href="{% url 'msgr:chat' join.chat.pk %}">
            {% if profile != user.profile %}
                {{ profile.get_full_name }}
            {% else %}
                Saved Messages
            {% endif %}
        </a>
    </div>
    {% endwith %}
    {% with unread_count=join.get_unread_count %}
    {% if unread_count %}
    <div class="unread-count">
        {{ unread_count }}
    </div>
    {% endif %}
    {% endwith %}
    <div class="chat-date">
        {{ join.chat.lat|date:"H:i m/d" }}
    </div>
</div>
{% empty %}
<div class="chat">
    You don't have any chats.
</div>
{% endfor %}
<hr>

{% endblock %}

msgr/templates/msgr/messages_list.html
{% load message_content_filters %}

{% for m in message_list %}
{% if m.sender == user %}
<div onclick="open_modal('{{ m.pk }}')" id="m-{{ m.pk }}" class="message right">
{% else %}
<div id="m-{{ m.pk }}" class="message left">
    <a href="{% url 'msgr:profile' m.sender.profile.pk %}" class="profile-link">
        <b>{{ m.sender.profile.get_short_name }}:</b>
    </a>
{% endif %}
    <pre>{{ m.content|inline_id }}</pre>
    <span hidden class="m-date">{{ m.send_time|date:"F d" }}</span>
    <span class="detail">
        <sub class="m-time">{{ m.send_time|time:"H:i" }}</sub>
        {% if m.sender == user %}
            <sub id="tick-{{ m.pk }}">
            {% if m.is_seen %}
                ✓✓
            {% else %}
                ✓
            {% endif %}
            </sub>
        {% endif %}
    </span>
</div>
{% endfor %}

msgr/templates/msgr/profile_page.html
{% extends 'base.html' %}
{% load static %}
{% load image_url_tags %}
{% load message_content_filters %}

{% block style %}
<link rel="stylesheet" href="{% static 'msgr/css/profile_page.css' %}">
{% endblock %}

{% block title %}{{ object.first_name }} - msgr{% endblock %}
{% block h1 %}{% endblock %}

{% block content %}

<h1>
    {{ object.first_name }}
{% if object.last_name %}
    {{ object.last_name }}
{% endif %}
</h1>

<img src="{% get_profile_pic object.picture %}" alt="profile picture" class="profile-pic">

<p>
{% if object.identifier %}
    @{{ object.identifier }}<br>
{% endif %}
{% if object.biography %}
    {{ object.biography|inline_id }}<br>
{% endif %}
</p>

<form method="post" action="{{ request.get_full_path }}">
    {% csrf_token %}
    <input type="submit" value="Chat">
</form>

{% endblock %}

msgr/templates/msgr/search_form.html
<div class="search-form">
    <form method="get" action="{% url 'msgr:search' %}">
        {{ search_form.q }}
        <input type="submit" value="Search">
    </form>
</div>

msgr/templates/msgr/search_page.html
{% extends 'base.html' %}
{% load static %}
{% load image_url_tags %}

{% block style %}
<link rel="stylesheet" href="{% static 'msgr/css/search_form.css' %}">
{% endblock %}

{% block title %}search - msgr{% endblock %}
{% block h1 %}<h1>Search for users</h1>{% endblock %}

{% block content %}

{% include 'msgr/search_form.html' %}

<ul>
{% for user in profile_list %}
    <li>
        <img src="{% get_profile_pic user.picture True %}" alt="profile thumbnail" class="thumbnail">
        <a href="{% url 'msgr:profile' user.pk %}">{{ user.get_full_name }}</a>
    </li>
{% endfor %}
</ul>
<hr>

{% endblock %}